CREATE TABLE IF NOT EXISTS SERIAL
(
  ID           INT PRIMARY KEY IDENTITY,
  NAME         VARCHAR(200) NOT NULL,
  PUBLISH_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_SERIAL
(
  ID           INT PRIMARY KEY IDENTITY,
  NAME         VARCHAR(200) NOT NULL,
  EPISODE      VARCHAR(4),
  LAST_UPDATED TIMESTAMP,
  SERIAL_ID    INT          NOT NULL,
  FOREIGN KEY (SERIAL_ID) REFERENCES SERIAL (ID)
);

CREATE TABLE IF NOT EXISTS USER_SERIAL_NOTIFICATION
(
  ID             INT PRIMARY KEY IDENTITY,
  TYPE           VARCHAR(100) NOT NULL,
  EPISODE        VARCHAR(4),
  LAST_UPDATED   TIMESTAMP,
  USER_SERIAL_ID INT,
  FOREIGN KEY (USER_SERIAL_ID) REFERENCES USER_SERIAL (ID)
);

